#!/bin/sh

DEVICE="HB-OU-RGB-CAMPFIRE"
DEVICE_IMG=hb-ou-rgb-campfire.png
DEVICE_THUMB=hb-ou-rgb-campfire_thumb.png
DEVICE_DESC="mains powered campfire with WS2812B RGB LED"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

### Edit webui.js ###
webuiFile="/www/webui/webui.js"

webuiSearchBegin="DEV_HIGHLIGHT[[:space:]]*=[[:space:]]*new Array();"
webuiInsert="\n"
webuiInsert="${webuiInsert}DEV_HIGHLIGHT['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_LIST.push('$DEVICE');\n"
webuiInsert="${webuiInsert}DEV_DESCRIPTION['$DEVICE']='$DEVICE_DESC';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['50'] = '\/config\/img\/devices\/50\/$DEVICE_THUMB';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['250'] = '\/config\/img\/devices\/250\/$DEVICE_IMG';"

if [ -z "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

##########################################################################################################################

DEVICE="HB-OU-RGB-CAMPFIRE-BAT"
DEVICE_IMG=hb-ou-rgb-campfire-bat.png
DEVICE_THUMB=hb-ou-rgb-campfire-bat_thumb.png
DEVICE_DESC="battery powered campfire with WS2812B RGB LED"

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

### Edit webui.js ###
webuiFile="/www/webui/webui.js"

webuiSearchBegin="DEV_HIGHLIGHT[[:space:]]*=[[:space:]]*new Array();"
webuiInsert="\n"
webuiInsert="${webuiInsert}DEV_HIGHLIGHT['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_LIST.push('$DEVICE');\n"
webuiInsert="${webuiInsert}DEV_DESCRIPTION['$DEVICE']='$DEVICE_DESC';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['50'] = '\/config\/img\/devices\/50\/$DEVICE_THUMB';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['250'] = '\/config\/img\/devices\/250\/$DEVICE_IMG';"

if [ -z "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi